name: Dependency Submission

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
      with:
        # Profiler plugins do not expose the dependencies to the runtime, so the versions used for the build
        # do not affect the execution. At the same time, we might need to build plugins for different thirdparty
        # versions, so we intentionally exclude :plugins:* projects from the submitted dependencies
        dependency-graph-exclude-projects: |
          :plugins:.*
